### ISSUE TITLE
Не обновляется файл скриптов (scripts.min.js) повторном изменении

### ISSUE THREAD

**Issue by stephan9696** [agragregra/OptimizedHTML-5#1]
При первом запуске галпа и внесении правок в файл custom.js все работает как нужно. Но при повторном внесении правок в данный файл и сохранении изменений не релоадиться сайт и не обновляется scripts.min.js

Галп шаблон проверил, вроде бы никаких ошибок нет.

**Comment by stephan9696** [comment]
Нашел. На 102 строке вы вотчите common.js, а не _custom.js

Нужно исправить на: gulp.watch(['libs/**/*.js', 'app/js/_custom.js'], gulp.parallel('scripts'));

**Comment by agragregra** [comment]
Спасибо.
