### ISSUE TITLE
Ошибка при установке npm модулей и запуске gulp

### ISSUE THREAD

**Issue by S1AnGeR** [agragregra/OptimizedHTML-5#11]
**Добрый день. Пытаюсь установить модули для optimizedHTML-5 .** 

### **Сначала делаю npm i :**

` npm i
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated lodash.createcallback@2.4.4: This package is discontinued. Use lodash.iteratee@^4.0.0.

> node-sass@4.12.0 install C:\OSPanel\domains\aaa\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\desun\AppData\Roaming\npm-cache\node-sass\4.12.0\win32-x64-72_binding.node

> sharp@0.21.3 install C:\OSPanel\domains\aaa\node_modules\sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached C:\Users\desun\AppData\Roaming\npm-cache\_libvips\libvips-8.7.0-win32-x64.tar.gz
info sharp Creating C:\OSPanel\domains\aaa\node_modules\sharp\build\Release
info sharp Copying DLLs from C:\OSPanel\domains\aaa\node_modules\sharp\vendor\lib to C:\OSPanel\domains\aaa\node_modules\sharp\build\Release
prebuild-install WARN install No prebuilt binaries found (target=12.12.0 runtime=node arch=x64 libc= platform=win32)

C:\OSPanel\domains\aaa\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Users\desun\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\desun\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\desun\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\desun\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Users\desun\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\desun\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\OSPanel\domains\aaa\node_modules\sharp
gyp ERR! node -v v12.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
npm WARN optimizedhtml@5.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.21.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.21.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\desun\AppData\Roaming\npm-cache\_logs\2019-10-16T20_27_29_659Z-debug.log
`

### **На этапе запуска gulp :**

`$ gulp
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'gulp-responsive'
Require stack:
- C:\OSPanel\domains\aaa\gulpfile.js
- C:\Users\desun\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^4.0.0\index.js
- C:\Users\desun\AppData\Roaming\npm\node_modules\gulp-cli\index.js
- C:\Users\desun\AppData\Roaming\npm\node_modules\gulp-cli\bin\gulp.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\OSPanel\domains\aaa\gulpfile.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\OSPanel\\domains\\aaa\\gulpfile.js',
    'C:\\Users\\desun\\AppData\\Roaming\\npm\\node_modules\\gulp-cli\\lib\\versioned\\^4.0.0\\index.js',
    'C:\\Users\\desun\\AppData\\Roaming\\npm\\node_modules\\gulp-cli\\index.js',
    'C:\\Users\\desun\\AppData\\Roaming\\npm\\node_modules\\gulp-cli\\bin\\gulp.js'
  ]
}
`

**Comment by Hasget** [comment]
Если работаете под Windows следуйте инструкции https://github.com/nodejs/node-gyp#on-windows

**Comment by onekrag** [comment]
Такая же ситуация. Как решили проблему?

**Comment by onekrag** [comment]
> **Добрый день. Пытаюсь установить модули для optimizedHTML-5 .**
> 
> ### **Сначала делаю npm i :**
> ` npm i
> npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
> npm WARN deprecated lodash.createcallback@2.4.4: This package is discontinued. Use lodash.iteratee@^4.0.0.
> 
> > node-sass@4.12.0 install C:\OSPanel\domains\aaa\node_modules\node-sass
> > node scripts/install.js
> 
> Cached binary found at C:\Users\desun\AppData\Roaming\npm-cache\node-sass\4.12.0\win32-x64-72_binding.node
> 
> > sharp@0.21.3 install C:\OSPanel\domains\aaa\node_modules\sharp
> > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
> 
> info sharp Using cached C:\Users\desun\AppData\Roaming\npm-cache_libvips\libvips-8.7.0-win32-x64.tar.gz
> info sharp Creating C:\OSPanel\domains\aaa\node_modules\sharp\build\Release
> info sharp Copying DLLs from C:\OSPanel\domains\aaa\node_modules\sharp\vendor\lib to C:\OSPanel\domains\aaa\node_modules\sharp\build\Release
> prebuild-install WARN install No prebuilt binaries found (target=12.12.0 runtime=node arch=x64 libc= platform=win32)
> 
> C:\OSPanel\domains\aaa\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Users\desun\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild ) else (node "C:\Users\desun\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
> gyp ERR! configure error
> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
> gyp ERR! stack at PythonFinder.failNoPython (C:\Users\desun\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
> gyp ERR! stack at PythonFinder. (C:\Users\desun\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
> gyp ERR! stack at C:\Users\desun\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:282:31
> gyp ERR! stack at FSReqCallback.oncomplete (fs.js:158:21)
> gyp ERR! System Windows_NT 10.0.18362
> gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\desun\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\OSPanel\domains\aaa\node_modules\sharp
> gyp ERR! node -v v12.12.0
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
> npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
> npm WARN optimizedhtml@5.0.0 No repository field.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! sharp@0.21.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the sharp@0.21.3 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\desun\AppData\Roaming\npm-cache_logs\2019-10-16T20_27_29_659Z-debug.log
> `
> 
> ### **На этапе запуска gulp :**
> `$ gulp
> internal/modules/cjs/loader.js:797
> throw err;
> ^
> 
> Error: Cannot find module 'gulp-responsive'
> Require stack:
> 
> * C:\OSPanel\domains\aaa\gulpfile.js
> * C:\Users\desun\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned^4.0.0\index.js
> * C:\Users\desun\AppData\Roaming\npm\node_modules\gulp-cli\index.js
> * C:\Users\desun\AppData\Roaming\npm\node_modules\gulp-cli\bin\gulp.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:687:27)
>   at Module.require (internal/modules/cjs/loader.js:849:19)
>   at require (internal/modules/cjs/helpers.js:74:18)
>   at Object. (C:\OSPanel\domains\aaa\gulpfile.js:11:18)
>   at Module._compile (internal/modules/cjs/loader.js:956:30)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
>   at Module.load (internal/modules/cjs/loader.js:812:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:724:14)
>   at Module.require (internal/modules/cjs/loader.js:849:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>   'C:\OSPanel\domains\aaa\gulpfile.js',
>   'C:\Users\desun\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^4.0.0\index.js',
>   'C:\Users\desun\AppData\Roaming\npm\node_modules\gulp-cli\index.js',
>   'C:\Users\desun\AppData\Roaming\npm\node_modules\gulp-cli\bin\gulp.js'
>   ]
>   }
>   `

Такая же ситуация. Как решили проблему?

**Comment by S1AnGeR** [comment]
@onekrag проблема решилась путём перехода на NodeJS 10.X и понижением версии gulp на 3.9.1.
