### ISSUE TITLE
Build without rsync

### ISSUE THREAD

**Issue by ibogdanovk** [agragregra/OptimizedHTML-5#16]
Мой хостинг не поддерживает доступ по ssh, поэтому я не могу использовать rsync для деплоя. Вы не могли подсказать как я могу собрать проект локально, чтобы потом уже вручную загрузить на хостинг?

**Comment by agragregra** [comment]
Проект уже собран и находится в app/

**Comment by ibogdanovk** [comment]
Понял, мой косяк)
