### ISSUE TITLE
Сборка проекта

### ISSUE THREAD

**Issue by Thr0TT1e** [agragregra/OptimizedHTML-5#19]
Доброго времени суток!

Подскажите, пожалуйста, как прописать в gulp'е таск для сборки?

Раньше использовал:
`gulp.task('build', gulp.parallel('prebuild', 'clean', 'img', 'styles', 'scripts'));`

Теперь не понимаю как написать новый такс по сборке проекта. Данное решение нужно для сборки проекта на сервисе [netlify.com](http://netlify.com)

**Comment by agragregra** [comment]
Проект уже собран в папке app. Всё автоматически и сразу.
