### ISSUE TITLE
Почему из стартового шаблона убрали lazy load?

### ISSUE THREAD

**Issue by lvan226** [agragregra/OptimizedHTML-5#21]
Здравствуйте Алексей, не совсем понял почему убрали lazy load из шаблона? С ним возникли какие-то проблемы? Хочу использовать ваш шаблон в своих проектах, но опыта у меня только полгода. Нашел последний коммит где есть lazy load, могу ли я взять его от туда и добавить в последнюю версию?

**Comment by agragregra** [comment]
Лучше использовать плагин. Метод от Google работает пока не везде.

**Comment by lvan226** [comment]
Ясно спасибо

**Comment by nikolays93** [comment]
Какой плагин порекомендуете?

**Comment by agragregra** [comment]
verlok/lazyload
