### ISSUE TITLE
Не работает насыщенность шрифта (font-weight) в IE11 и Firefox

### ISSUE THREAD

**Issue by leon9208** [agragregra/OptimizedHTML-5#24]
В файле **_config.sass** если убрать свойство **local($fname)**, то насыщенность (font-weight) работает везде.

```
@mixin font($fname, $fstyle, $fweight, $furl)
	@font-face
		font-family: $fname
		font-style: $fstyle
		font-weight: $fweight
		font-display: swap
		src: local($fname), url($furl) format('woff2')
```

**Comment by agragregra** [comment]
А зачем убирать это свойство? Называйте шрифты так, как они называются локально, данное свойство необходимо.

**Comment by agragregra** [comment]
Что касается насыщенности, видимо вы не подключили в проект другие начертания.

**Comment by leon9208** [comment]
Вот как у меня это выглядит сейчас, для IE я дополнил .woff формат, а так изменения незначительные.

`@mixin font($fname, $fstyle, $fweight, $furl)
	@font-face
		font-family: '#{$fname}'
		src: url('#{$furl}.woff2') format('woff2'), url('#{$furl}.woff') format('woff')
		font-style: $fstyle
		font-weight: $fweight
		font-display: swap

@include font('Geometria', normal, 400, '../fonts/Geometria')
@include font('Geometria', normal, 500, '../fonts/Geometria-Medium')
@include font('Geometria', normal, 700, '../fonts/Geometria-Bold')
@include font('Geometria', normal, 800, '../fonts/Geometria-ExtraBold')
@include font('Geometria', normal, 900, '../fonts/Geometria-Heavy')`

**Comment by leon9208** [comment]
> Что касается насыщенности, видимо вы не подключили в проект другие начертания.

Проблема в том что не работало только в IE 11 и Firefox, а в Google Chrome/Opera/Яндекс работало

**Comment by leon9208** [comment]
> А зачем убирать это свойство? Называйте шрифты так, как они называются локально, данное свойство необходимо.

Касаемо **local()**, в начале должен быть поиск шрифта в **пк** у пользователя, если шрифт не найден, то должны загружаться веб-шрифты, но почему-то в Firefox и IE11 этого не происходит. Ради интереса скачал ваш стартовый шаблон заново и без внесения изменений открыл в Firefox, аналогичная проблема присутствует, думал я у себя в проекте накосячил, но нет.

**Comment by agragregra** [comment]
Странно.

**Comment by lvan226** [comment]
Та же проблема со шрифтами

**Comment by agragregra** [comment]
Локальный шрифт и шрифт, который вы загружаете через font-face может отличаться, несмотря на одинаковое именование.
![alt text](https://webdesign-master.ru/img/other/font.gif)
