### ISSUE TITLE
Долго компилируется SASS

### ISSUE THREAD

**Issue by fiercesaint** [agragregra/OptimizedHTML-5#25]
Добрый день. Давно пользуюсь вашими сборками, всегда SASS компилировался быстро, меньше 1 сек. В последней версии, когда поменялась структура и стало возможным выбирать между less, sass и т.д., у меня SASS стал все дольше и дольше компилироваться. Подскажите, пожалуйста, в чем может быть проблема?

**Comment by agragregra** [comment]
Здравствуйте. У вас точно не менялась конфигурация компьютера?

**Comment by fiercesaint** [comment]
Нет. Когда я скачиваю предыдущую версию, все также быстро работает (

**Comment by fiercesaint** [comment]
Работаю в PhpStorm все время и никогда с предыдущей версией не было проблем. А тут компиляция SASS доходит аж до 10 секунд (

**Comment by agragregra** [comment]
Это очень странно. Можете мне отправить проект-пример на почту agragregra@ya.ru я потестирую

**Comment by agragregra** [comment]
Мною были протестированы 5 включенных файла, состоящие из 10 000 строк кода каждый. Компиляция занимает 200мс. Протестировал всесторонне, что-то у вас не так.

**Comment by SkiperX** [comment]
Отключение опции "safe write" в настройках PHPStorm должно помочь.

**Comment by fiercesaint** [comment]
Спасибо большое!!!
