### ISSUE TITLE
Не работают миксины Bootstrap

### ISSUE THREAD

**Issue by second1996** [agragregra/OptimizedHTML-5#26]
**Обновил версию OH5** и при попытке изменить переменную  `$gutter` на 20 px — не работает.

**Миксины игнорируються почему-то.**
И эти переменные так же в файле `_config.sass`:
`$container-max-widths: (sm: 540px, md: 720px, lg: 1140px, xl: 1390px)`
`$grid-breakpoints: (xs: 0, sm: 576px, md: 768px, lg: 992px, xl: 1420px)`

Пробывал на голую OH5 установку — не помогло.

Не могу понять, где проблема. Подключал разные варианты миксинов от Bootstrap в файл `_config.sass`, всё безуспешно.
Но, если менять в файлах Bootstrap, то всё работает как часики. 

_Алексей, в чем может быть проблема?_

**Comment by agragregra** [comment]
Нужно менять не $gutter, а переменную, принимающую значение $grid-gutter-width

**Comment by second1996** [comment]
@agragregra, да и эту тоже пробывал. Не работает.
`$container-max-widths` и `$grid-breakpoints:` так же игнорируются.

**Comment by agragregra** [comment]
Сделайте рефакторинг своего кода.

**Comment by second1996** [comment]
@agragregra я скачал OH5 сборку, установил npm пакеты, запустил `gulp` и просто решил сменить `$grid-gutter-width` на, к примеру, 80 px. 

Padding'и при это как были по 15 px (то есть `$grid-gutter-width` = 30px), так и остались. Перезапуск `gulp` не решает проблемы.

**Comment by agragregra** [comment]
Дак по-умолчанию Bootstrap отключен. Ознакомьтесь с уроком более внимательно: https://webdesign-master.ru/blog/tools/2019-07-15-optimizedhtml-5.html

**Comment by second1996** [comment]
@agragregra, я не впервые Вашу сборку использую :)

Кончено, что первым делом, что я сделал, это подключил импорт `bootstrap-grid.scss` и `_sizing.scss`

**Comment by agragregra** [comment]
Fixed. Спасибо.

**Comment by second1996** [comment]
@agragregra Отлично сработано, Алексей! Теперь всё отлично работает :)
Спасибо!
