### ISSUE TITLE
gulp-ssi

### ISSUE THREAD

**Issue by ABabiy** [agragregra/OptimizedHTML-5#27]
Можно ли для проектов с большим объёмом кода сделать разбивку на блоки и вставку их через данный плагин?
У меня не получилось. Возможно Вы сможете сделать?

**Comment by agragregra** [comment]
Какого именно кода? Препроцессоры по-умолчанию поддерживают include.

**Comment by ABabiy** [comment]
> Какого именно кода? Препроцессоры по-умолчанию включают в себя.

Это же SSI - для HTML кода соответственно

**Comment by agragregra** [comment]
Возможно.
