### ISSUE TITLE
Проблема datatables.js

### ISSUE THREAD

**Issue by vezhevich** [agragregra/OptimizedHTML-5#37]
В новой сборке OptimizedHTML-5 существует какая то проблема. Протестировал все на старой сборке"version": "3.0.0", все работает отлично. Проблема в следующем: при подключении плагина https://datatables.net появляется проблема горизонтального скрола, при скроле таблица скачет в начало, на мобиле вообще пользоваться невозможно. На старой версии сборки все работает отлично.

**Comment by agragregra** [comment]
Используйте старую, 4 версию. Там все старые методы подключения плагинов работают.

**Comment by vezhevich** [comment]
Понятно, планируется в новой версии правка данного бага? Очень уж нравится свежая версия

**Comment by agragregra** [comment]
В новой версии багов нет, всё протестирвовано, JS работает модульно, используйте модуль вашего плагина, если разработчики его написали. Если нет, переработайте стартер под работу старым методом подключения JS файлов.

**Comment by agragregra** [comment]
Ну или попробуйте require() вашей библиотеки. jQuery должен быть импортирован как модуль.

**Comment by vezhevich** [comment]
Хорошо, попробую, спасибо!

**Comment by agragregra** [comment]
https://datatables.net/forums/discussion/53446/es6-webpack-environment-import-editor-plugin
Может этот тред поможет вам.

**Comment by agragregra** [comment]
Проверил проект, который ранее не использовал импорты в JS. Миграция прошла довольно успешно, вот код интеграции в app.js:
`import $ from 'jquery'; window.jQuery = $; window.$ = $ // import jQuery module (npm i -D jquery)

require('~/app/libs/mmenu/js/jquery.mmenu.all.min.js')
require('~/app/libs/owl.carousel/owl.carousel.min.js')
require('~/app/libs/fotorama/fotorama.js')
require('~/app/libs/selectize/js/standalone/selectize.min.js')
require('~/app/libs/equalHeights/equalheights.js')`

**Comment by vezhevich** [comment]
Спасибо, буду использовать
