### ISSUE TITLE
Баг с обработчиками событий browsersync

### ISSUE THREAD

**Issue by iTemes** [agragregra/OptimizedHTML-5#39]
Мб кто сталкивался, при разработке на запущенном дев сервере на http://localhost:3000/. все обработчики событий срабатывают 2-3 раза, на deploy версии все ок

**Comment by iTemes** [comment]
p.s решилось в настройках Browsersync, выключением "Mirror scroll position across devices"

**Comment by agragregra** [comment]
ghostMode: { clicks: false }
Я правильно понимаю, это ваше решение? Спасибо.

**Comment by iTemes** [comment]
> 
> 
> ghostMode: { clicks: false }
> Я правильно понимаю, это ваше решение? Спасибо.

Да, все верно, добавил этот параметр в browserSync и теперь все работает корректно без mirroring для кликов.
