### ISSUE TITLE
Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (88)

### ISSUE THREAD

**Issue by devellopah** [agragregra/OptimizedHTML-5#40]
На текущий момент в проекте присутствует `node-sass@4.14.1` как зависимость пакета `gulp-sass@4.1.0`(`npm ls node-sass`).
У меня стоит **15.5.1** версия nodejs, поэтому выходит эта ошибка (я это понял со временем, по мере сбора информации). Чтобы избавиться от ошибки, нужно откатиться к 14 версии nodejs (я откатился к **14.15.4**).
Разные версии [node-sass](https://github.com/sass/node-sass/releases) поддерживают разные версии nodejs (также имеет значение os). Версия **4.14.1** поддерживает версии nodejs вплоть до 14 (включительно). Предлагаю в package.json добавить строчку (10-ку поддерживают все os из _Supported Environments_)

```json
"engines": {
  "node": ">=10 <=14"
},
```
Также нужно создать файл `.npmrc` с содержимым
`engine-strict=true`

Данная мера позволит выбрасывать ошибку и прекращать дальнейшую установку пакетов, если nodejs не соответствует указанному ограничению.

p.s. Придётся отслеживать версию node-sass: если обновиться до 5, то ограничение будет `"node": ">=10 <=15"`.

**Comment by agragregra** [comment]
Ну да, я всегда рекомендую использовать LTS версию.

**Comment by devellopah** [comment]
Добавь в `readme`, мол, при возникновении такой-то ошибки, проверьте, версию `node-sass` командой `npm ls node-sass` и убедитесь, что ваша версия `nodejs` [удовлетворяет](https://github.com/sass/node-sass/releases) требование `node-sass`.
Мне бы здорово помогло наличие такой информации в `readme`.
