### ISSUE TITLE
Не работает условия if

### ISSUE THREAD

**Issue by fiercesaint** [agragregra/OptimizedHTML-5#41]
Добрый день.
Почему-то не работает условие if для переменных.

#set var="loginStatus" value="off"
#if expr="$loginStatus == 'on'"
ON
else
OFF
endif

В коде не писал <!-- т.к. скрывается

Выводит на экран и ON и OFF. Как-будто код условий игнорируется.

Подскажите, пожалуйста, в чем может быть проблема?

**Comment by fiercesaint** [comment]
#set var="loginStatus" value="off"
#if expr="$loginStatus == 'on'"
ON
else
OFF
endif

**Comment by agragregra** [comment]
Здравствуйте.
1. Следует писать не <!--, а <!--#
2. on и off могут являться частью SSI, попробуйте задать другие булёвые переменные, 1-0, например.
3. "В коде не писал <!-- т.к. скрывается" эта часть текста меня смущает. Без <!--# SSI не работает.

**Comment by fiercesaint** [comment]
Вот мой код:

`<!--#set var="loginStatus" value="test" -->`
`<!--#if expr="$loginStatus == 'test2'"-->`
ON
`<!--#else-->`
OFF
`<!--#endif-->`

выводит и ON и OFF

**Comment by agragregra** [comment]
В течение часа разберусь. Сразу скажу, что синтаксис не соблюдён. Перед --> должен быть пробел.

**Comment by fiercesaint** [comment]
Поставил пробел. Теперь пишет
$loginStatus is not defined

`<!--#set var="loginStatus" value="test" -->`
`<!--#if expr="$loginStatus == 'test2'" -->`
ON
`<!--#else -->`
OFF
`<!--#endif -->`

**Comment by agragregra** [comment]
В настоящее время работают простые булёвые сравнения:







Кроме того, между директивами if/else/endif нельзя вставлять обычный текст, это работает не как PHP. Для более сложных задач рекомендую присмотреться к какому-либо back-end языку.

**Comment by fiercesaint** [comment]
Спасибо большое за подробное объяснение.
