### ISSUE TITLE
ошибка is not defined

### ISSUE THREAD

**Issue by vezhevich** [agragregra/OptimizedHTML-5#42]
http://joxi.ru/xAeYLp6HX156PA подключаю библиотеку
http://joxi.ru/brRea3GuOp6VRA вызываю
http://joxi.ru/LmGyaYGSl8Db7A ошибка

вот этот плагин https://github.com/abpetkov/powerange

Что делаю не так?

Другие подключенные плагины работают, то что сверху на скрине
Также web pack ругался на лимит подключенных бандлов (я полечил следующим образом performance: {hints: false} вроде перестал ругаться)

**Comment by vezhevich** [comment]
Через такую конструкцию(установил компонент через npm) получилось все.
import Powerange from 'abpetkov-powerange'

**Comment by hasenov** [comment]
а если нет через npm, только вендор, тогда ошибка и ничего не работает
