### ISSUE TITLE
Как отслеживать ошибки если js минифицируется сразу?

### ISSUE THREAD

**Issue by vezhevich** [agragregra/OptimizedHTML-5#46]
http://joxi.ru/Y2Le6dBuEXWGlA

**Comment by vezhevich** [comment]
мне кажется раньше было удобнее, когда библиотеки минифицировались, а common.js там где пишешь отсебятину оставался нормальным

**Comment by agragregra** [comment]
В настройках webpack (gulpfile) указываете не production, а development.

**Comment by alex-grsm** [comment]
хорошо бы сделать, что бы библиотеки сжимались, а отсебятина оставалась в исходном виде, особенно если передавать фронт прогеру на натяжку. development такой себе вариант, пока в голову пришло только закидывать отсебятину во второй фаил .js

**Comment by alex-grsm** [comment]
минификацию можно отрубить 
optimization: { minimize: false },

**Comment by vezhevich** [comment]
понятно, взял на вооружение, но вариант со вторым файлом из отсебятины наверное будет лучше!

**Comment by agragregra** [comment]
Вообще не понял, в чём проблема ))
Сделайте отдельный custom.js и пишите в нём свой код. Разве есть какие-то рамки? Делайте, как вам удобнее.

**Comment by vezhevich** [comment]
да это не проблема, просто пересел с одной версии сборки (где все было так как надо) на другую где да, нужно будет подстроить все под себя, спасибо за сборку!

**Comment by vezhevich** [comment]
> Вообще не понял, в чём проблема ))
> Сделайте отдельный custom.js и пишите в нём свой код. Разве есть какие-то рамки? Делайте, как вам удобнее.

как в gulpfile.js  в таске все это прописать чтобы для отбельного файла все работало, что бы он не минифицировался и не включался в app.min.js

**Comment by vezhevich** [comment]
> > Вообще не понял, в чём проблема ))
> > Сделайте отдельный custom.js и пишите в нём свой код. Разве есть какие-то рамки? Делайте, как вам удобнее.
> 
> как в gulpfile.js в таске все это прописать чтобы для отбельного файла все работало, что бы он не минифицировался и не включался в app.min.js

добавить новый таск для этого отдельного файла?

**Comment by hasenov** [comment]
Этот шаблон ломает подключение плагинов. подключаю любой плагин, вызываю функцию и он not defined.
