### ISSUE TITLE
События срабатывают три раза

### ISSUE THREAD

**Issue by rah-emil** [agragregra/OptimizedHTML-5#47]
Мои скрипты почти всегда 3 раза срабатывают. Проблема присутствует с разных ПК. Это происходит только когда запущен browser sync. В чём может быть дело?

**Comment by alex-grsm** [comment]
строку добавь эту https://prnt.sc/10w4l4b

**Comment by agragregra** [comment]
> строку добавь эту https://prnt.sc/10w4l4b
> 
> ghostMode: { clicks: false },

она есть)

**Comment by alex-grsm** [comment]
не повезло тебе тогда) перепроверил у себя вот (тоже был такой прикол) - все работает ровно.
такой кодик у меня:

function browsersync() {
	browserSync.init({
		ghostMode: { clicks: false },
		server: {
			baseDir: 'app/',
			middleware: bssi({ baseDir: 'app/', ext: '.html' })
		},
		//tunnel: 'ruslanloveredesign', // Attempt to use the URL https://yousutename.loca.lt
		notify: false,
		online: true
	})
}

**Comment by rah-emil** [comment]
> строку добавь эту https://prnt.sc/10w4l4b
> 
> ghostMode: { clicks: false },

У меня нет этого
Спасибо, я посмотрю попозже и отпишусь, если что

**Comment by rah-emil** [comment]
> строку добавь эту https://prnt.sc/10w4l4b
> 
> ghostMode: { clicks: false },
Помогло
