### ISSUE TITLE
not defined

### ISSUE THREAD

**Issue by hasenov** [agragregra/OptimizedHTML-5#49]
при подключении js vendor плагинов, и их вызове выходит ошибка not defined.

**Comment by hasenov** [comment]
заметил что при сборке проекта, все плагины по странному минифицируются и из-за этого видимо всё ломается.

**Comment by makc9I** [comment]
Удалось как-то решить эту проблему? Я вот тоже пользуюсь этой сборкой. Отдаю вёрстку дальше на работу бекендерам, а они потом туда ни строчки своего js написать не могут, так как всё как-то очень изолированно получается.

**Comment by agragregra** [comment]
> Удалось как-то решить эту проблему? Я вот тоже пользуюсь этой сборкой. Отдаю вёрстку дальше на работу бекендерам, а они потом туда ни строчки своего js написать не могут, так как всё как-то очень изолированно получается.

Дак для этого же есть OptimizedHTML 4, я там обновляю все модулю регулярно. Вы смотрите, для каких целей то сборка. Если бэкендеры не могу разобраться с модульным JS, используйте 4-ю версию. Хотя странно, что они не могут с ним разобраться.

**Comment by hasenov** [comment]
> Удалось как-то решить эту проблему? Я вот тоже пользуюсь этой сборкой. Отдаю вёрстку дальше на работу бекендерам, а они потом туда ни строчки своего js написать не могут, так как всё как-то очень изолированно получается.

этой сборкой перестал пользоваться, перешёл на https://github.com/WeAreAthlon/frontend-webpack-boilerplate и немного её изменил под себя. Все нужные задачи выполняет, проблем с современным ES6 JS больше нет.
