### ISSUE TITLE
Проблемы с плагином Swiper Slider

### ISSUE THREAD

**Issue by mashanlo** [agragregra/OptimizedHTML-5#50]
У меня одного так? Проблема в том что пагинация и кнопки навигации не работают.

**Comment by agragregra** [comment]
Обновил. Проверил. Всё работает.

**Comment by mashanlo** [comment]
Еще раз попробовал. Не работает. Вот ссылка на [гит](https://github.com/mashanlo/swiper)

**Comment by AVZuykov** [comment]
Попробуй импортировать `swiper/swiper-bundle`, у меня все заработало.

**Comment by mashanlo** [comment]
Заработало)
