### ISSUE TITLE
Подключение шрифтов

### ISSUE THREAD

**Issue by ABabiy** [agragregra/OptimizedHTML-5#6]
Здравствуйте!
Шрифты находятся в папке app/fonts/_src а в _fonts.sass  подключение происходит из папки без _src 
`@include font('Roboto', normal, 400, '../fonts/roboto-regular-webfont.woff2')`
Соответственно ошибка в консоли браузера - шрифт не найден
по идее должен отрабатывать скрипт какой-то и шрифты после обработки должны попадать в fonts
P.S.
Сайт не работает...

**Comment by nikolays93** [comment]
А файл стилей ведь лежит в папке css, так что все нормально.
https://c.radikal.ru/c31/1907/c2/ac26c291df20.png

**Comment by ABabiy** [comment]
![32082-clip-17kb 1](https://user-images.githubusercontent.com/4932289/61966632-c20f6c00-afdb-11e9-8a5a-0b0d28d305c9.png)
Вот где по-умолчанию шрифты находятся

**Comment by nikolays93** [comment]
кхм, может у вас старая репа? https://github.com/agragregra/OptimizedHTML-5/tree/master/app/fonts

**Comment by ABabiy** [comment]
Даже в этом репозитории шрифты и в корне и в _src А зачем _src ?

**Comment by agragregra** [comment]
_readme.txt
