### ISSUE TITLE
Very nice template, but please update it

### ISSUE THREAD

**Issue by ander481** [agragregra/OptimizedHTML-5#63]
There is a completely mess with packages and new package updates including gulp.
Accoding to the new gulp documentation the syntax for gulpfile.js was significantly changed. e.g now you need to use
`const { src, dest, series } = require('gulp');`
instead of
`const { gulp, src, dest, series } = pkg`
(also, import is not used anymore)

Browser-sync is also using a new syntax now.
Example of the new gulp task from my project:
```
const bs = require('browser-sync').create();

function sync() {
    bs.init({
        watch: true,
        server: "app",
        files: [
            {
                match: ["*.html"],
                fn: function (event, file) {
                    /** Custom event handler **/
                },
                options: {
                    ignored: '*.txt'
                }
            }
        ]
    });
    bs.reload("*.html");
}
```

**Comment by agragregra** [comment]
Я не могу использовать require, так как требования изменились. Сейчас актуально использовать import. Ваш код устаревший.
