### ISSUE TITLE
Gulp async error

### ISSUE THREAD

**Issue by Dikht** [agragregra/OptimizedHTML-5#65]
Выдается ошибка при запуске gulp. 

```
webpack 5.94.0 compiled successfully
[13:38:39] Finished 'scripts' after 1.52 s
[13:38:39] Starting 'styles'...
[13:38:40] The following tasks did not complete: default, styles
Did you forget to signal async completion?
```

Каким образом нужно преобразовать gulpfile.js ?

**Comment by agragregra** [comment]
> Выдается ошибка при запуске gulp.
> 
> ```
> webpack 5.94.0 compiled successfully
> [13:38:39] Finished 'scripts' after 1.52 s
> [13:38:39] Starting 'styles'...
> [13:38:40] The following tasks did not complete: default, styles
> Did you forget to signal async completion?
> ```
> 
> Каким образом нужно преобразовать gulpfile.js ?

Преобразовывать gulpfile.js не нужно, просто проверьте, где у вас ошибка или опечатка в sass файлах.

**Comment by Dikht** [comment]
при использовании scss синтаксиса расширение файлов нужно менять на scss либо так и оставлять *.sass ?

**Comment by agragregra** [comment]
> при использовании scss синтаксиса расширение файлов нужно менять на scss либо так и оставлять *.sass ?

для синтаксиса sass используется расширение sass
для синтаксиса scss используется расширение scss
scss можно подключить в главный sass файл
scss автоматически подключается из папки blocks

**Comment by Dikht** [comment]
Спасибо за помощь и разъяснение
