### ISSUE TITLE
Media

### ISSUE THREAD

**Issue by ABabiy** [agragregra/OptimizedHTML-5#7]
Добрый день!
Хорошее ли это решение - добавлять к каждому элементу 
`+media-breakpoint-down(**)` ?
Во-первых добавляется очень много кода дублируемого - эти строчки для всех элементов, участвующих в адаптивности повторяются, во-вторых здорово было бы добавить gulp-sourcemaps чтобы понимать где искать в исходниках нужный код

**Comment by agragregra** [comment]
Здравствуйте.
Да, это великолепное решение. Код добавляется только к нужным элементам.
