### ISSUE TITLE
lazyLoad

### ISSUE THREAD

**Issue by IKEFERI** [agragregra/OptimizedHTML-5#9]
Алексей, здравствуйте! Я насчет плагина lazyload в новом шаблоне - почему на десктопе грузятся картинки формата x1, а на мобильных и прочих - x2(то есть картинки более высокого качества)? Так и должно быть?

**Comment by agragregra** [comment]
Здравствуйте. Как правильно, мобильные устройства имеют масштабирование интерфейса свыше 150%, соответственно, поэтому загружаются изображения высокого разрешения из @2x.
